# config.yaml
base_dir: "/home/pi/eink_calendar"
update_interval: 3600  # in seconds

# Calendar settings
ical_files_dir: "data/ics"
merged_calendar_file: "data/merged_calendar.json"
credentials_file: "data/credentials.json"  # iCloud credentials file
holiday_api_url: "https://date.nager.at/api/v3/PublicHolidays"

# Display settings
display_width: 800
display_height: 480
font_path: "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
output_image: "data/weekly_calendar_output.bmp"

# Testing flag – set to true when running on a desktop
test_mode: true